In [2]:
import numpy as np
import matplotlib.pyplot as plt
import cv2

In [4]:
x = np.zeros((3,5), dtype = np.uint8)
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [5]:
print(x.shape)

(3, 5)


In [6]:
print(x.dtype)

uint8


In [ ]:
print(x.T)
print(x.trasnpose())
print(np.transpose(x))

In [8]:
y = np.arange(12, dtype = np.uint8)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [14]:
y = y.reshape((3,4))
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
y[y>=9] = 0
print(y)

[[0 1 2 3]
 [4 5 6 7]
 [8 0 0 0]]


In [21]:
print(y * y)

[[ 0  1  4  9]
 [16 25 36 49]
 [64  0  0  0]]


In [22]:
print(y @ y.T)
print(np.dot(y, y.T))

[[ 14  38   0]
 [ 38 126  32]
 [  0  32  64]]
[[ 14  38   0]
 [ 38 126  32]
 [  0  32  64]]


imaging

In [ ]:
img_path = data/cat.jpg
img = plt.imread(img_path)
plt.imshow(img)
plt.show()

In [ ]:
t, l, b, r = 100, 250, 250, 400
crop = img[t:b, l:r]
plt.show(crop)

In [ ]:
img_open = cv.imread(img_path)
plt.imshow(img_opencv)
plt.show()

#cat is in the wrong color because not RGB color scheme

In [ ]:
#Reverse channels 
img_fixed = img_opencv[:,:,:,::-1]
plt.show(img_fixed)

In [ ]:
img_fixed = cv2.cvtColor(img_opencv, cv2.COLOR_BGR2RGB)
plt.imshow(img_fixed)